# CodeRabbit Configuration
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: en

reviews:
  # Enable automatic reviews on PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  # Review profile - chill is less strict
  profile: chill

  # Path filters - skip generated files
  path_filters:
    - "!**/*.min.js"
    - "!**/*.lock"
    - "!**/dist/**"
    - "!**/.claude/hooks/dist/**"

  # Request changes on critical issues
  request_changes_workflow: false

  # Enable high-level summary
  high_level_summary: true

  # Poem in reviews (fun but optional)
  poem: false

  # Review status (show progress)
  review_status: true

  # Collapse walkthrough for large PRs
  collapse_walkthrough: true

chat:
  # Enable chat in PR comments
  auto_reply: true

# Early access features
early_access: false
