#!/usr/bin/env python3
"""
Skill Initializer - Creates a new skill from template

Usage:
    init_skill.py <skill-name> --path <path>

Examples:
    init_skill.py my-new-skill --path skills/public
    init_skill.py my-api-helper --path skills/private
    init_skill.py custom-skill --path /custom/location
"""

import sys
from pathlib import Path


SKILL_TEMPLATE = """---
name: {skill_name}
description: [TODO: 1-3 sentences (50-150 words) describing what this skill does, when to use it, and key capabilities. Include specific trigger keywords users will say (e.g., "when users request", "for creating", "Excel spreadsheets"). Use third-person perspective: "This skill should be used when..." not "Use this skill when..."]
---

# {skill_title}

<!-- Generated by skill-creator v2.0 (2025-10-30) -->
<!-- Platform: Works on Claude Code (CLI/IDE) and Claude.ai (web/desktop app) -->

[Brief 1-2 sentence overview of the skill's purpose]

## When to Use This Skill

Use this skill when:
- [Specific trigger scenario 1 - be concrete]
- [Specific trigger scenario 2 - mention file types if relevant]
- [Specific trigger scenario 3 - include user phrases]

## How to Use This Skill

### Core Workflow

1. **[Step 1 Name]**: [Imperative instruction - verb-first]
   - Load `scripts/example.py` if using scripts
   - Reference `references/guide.md` for detailed info

2. **[Step 2 Name]**: [Imperative instruction]
   - Execute script function: `function_name(parameters)`
   - Apply guidelines from references

3. **[Step 3 Name]**: [Imperative instruction]
   - Use `assets/template.ext` as base if using assets
   - Generate final output

### Bundled Resources

Delete this section if not using bundled resources. Otherwise, document each resource:

- **`scripts/example.py`**: [What this script does and when to use it]
- **`references/guide.md`**: [What this reference contains and when to load it]
- **`assets/template.ext`**: [What this asset is and how to use it]

**Note:** Scripts execute when properly referenced in SKILL.md, on both Claude Code and Claude.ai platforms.

### Examples

**Example 1: [Scenario name]**

Input: "[Example user request - realistic phrasing]"

Process:
1. [What Claude should do first]
2. [What Claude should do next]
3. [Final step]

Output: [Expected result - be specific]

**Example 2: [Another scenario]**

Input: "[Another example request]"

Process:
1. [Step 1]
2. [Step 2]

Output: [Expected result]

## Best Practices

- [Best practice 1 - specific, actionable]
- [Best practice 2 - what to do/avoid]
- [Best practice 3 - common gotchas]

## Troubleshooting

| Issue | Solution |
|-------|----------|
| [Common issue 1] | [How to fix it] |
| [Common issue 2] | [How to resolve] |

---

## Before Packaging - Checklist

✅ Complete description (50-150 words with trigger keywords)
✅ Remove all [TODO] markers
✅ Add 2-3 concrete examples
✅ Document all bundled resources if using them
✅ Delete unused resource directories
✅ Test scripts independently if using them
✅ Keep under 5,000 words total

---

*Delete this checklist section before finalizing*
"""

EXAMPLE_SCRIPT = '''#!/usr/bin/env python3
"""
Example helper script for {skill_name}

This is a placeholder script - customize for your needs or delete if not using scripts.

Common script patterns by skill type:

1. Excel Generation (openpyxl):
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill

    def create_excel(title, data):
        wb = Workbook()
        ws = wb.active
        ws.title = title
        # Add headers, data, formatting
        return wb

2. PDF Manipulation (PyPDF2):
    from PyPDF2 import PdfReader, PdfWriter

    def process_pdf(input_path, output_path):
        reader = PdfReader(input_path)
        writer = PdfWriter()
        # Process pages
        with open(output_path, 'wb') as f:
            writer.write(f)

3. Data Processing:
    import json
    import csv

    def transform_data(input_file, output_file):
        # Load, transform, save
        pass

Dependencies: Document required packages in comments
Example: Dependencies: openpyxl>=3.1.0, pandas>=2.0.0
"""

def main():
    print("This is an example script for {skill_name}")
    print("Customize this script for your skill's needs")
    # TODO: Replace with actual implementation
    # - Add error handling
    # - Validate inputs
    # - Return meaningful results

if __name__ == "__main__":
    main()
'''

EXAMPLE_REFERENCE = """# Reference Documentation for {skill_title}

This is a placeholder for detailed reference documentation.
Replace with actual reference content or delete if not needed.

Example real reference docs from other skills:
- product-management/references/communication.md - Comprehensive guide for status updates
- product-management/references/context_building.md - Deep-dive on gathering context
- bigquery/references/ - API references and query examples

## When Reference Docs Are Useful

Reference docs are ideal for:
- Comprehensive API documentation
- Detailed workflow guides
- Complex multi-step processes
- Information too lengthy for main SKILL.md
- Content that's only needed for specific use cases

## Structure Suggestions

### API Reference Example
- Overview
- Authentication
- Endpoints with examples
- Error codes
- Rate limits

### Workflow Guide Example
- Prerequisites
- Step-by-step instructions
- Common patterns
- Troubleshooting
- Best practices
"""

EXAMPLE_ASSET = """# Example Asset File

This placeholder represents where asset files would be stored.
Replace with actual asset files (templates, images, fonts, etc.) or delete if not needed.

Asset files are NOT intended to be loaded into context, but rather used within
the output Claude produces.

Example asset files from other skills:
- Brand guidelines: logo.png, slides_template.pptx
- Frontend builder: hello-world/ directory with HTML/React boilerplate
- Typography: custom-font.ttf, font-family.woff2
- Data: sample_data.csv, test_dataset.json

## Common Asset Types

- Templates: .pptx, .docx, boilerplate directories
- Images: .png, .jpg, .svg, .gif
- Fonts: .ttf, .otf, .woff, .woff2
- Boilerplate code: Project directories, starter files
- Icons: .ico, .svg
- Data files: .csv, .json, .xml, .yaml

Note: This is a text placeholder. Actual assets can be any file type.
"""


def title_case_skill_name(skill_name):
    """Convert hyphenated skill name to Title Case for display."""
    return ' '.join(word.capitalize() for word in skill_name.split('-'))


def init_skill(skill_name, path):
    """
    Initialize a new skill directory with template SKILL.md.

    Args:
        skill_name: Name of the skill
        path: Path where the skill directory should be created

    Returns:
        Path to created skill directory, or None if error
    """
    # Determine skill directory path
    skill_dir = Path(path).resolve() / skill_name

    # Check if directory already exists
    if skill_dir.exists():
        print(f"❌ Error: Skill directory already exists: {skill_dir}")
        return None

    # Create skill directory
    try:
        skill_dir.mkdir(parents=True, exist_ok=False)
        print(f"✅ Created skill directory: {skill_dir}")
    except Exception as e:
        print(f"❌ Error creating directory: {e}")
        return None

    # Create SKILL.md from template
    skill_title = title_case_skill_name(skill_name)
    skill_content = SKILL_TEMPLATE.format(
        skill_name=skill_name,
        skill_title=skill_title
    )

    skill_md_path = skill_dir / 'SKILL.md'
    try:
        skill_md_path.write_text(skill_content)
        print("✅ Created SKILL.md")
    except Exception as e:
        print(f"❌ Error creating SKILL.md: {e}")
        return None

    # Create resource directories with example files
    try:
        # Create scripts/ directory with example script
        scripts_dir = skill_dir / 'scripts'
        scripts_dir.mkdir(exist_ok=True)
        example_script = scripts_dir / 'example.py'
        example_script.write_text(EXAMPLE_SCRIPT.format(skill_name=skill_name))
        example_script.chmod(0o755)
        print("✅ Created scripts/example.py")

        # Create references/ directory with example reference doc
        references_dir = skill_dir / 'references'
        references_dir.mkdir(exist_ok=True)
        example_reference = references_dir / 'api_reference.md'
        example_reference.write_text(EXAMPLE_REFERENCE.format(skill_title=skill_title))
        print("✅ Created references/api_reference.md")

        # Create assets/ directory with example asset placeholder
        assets_dir = skill_dir / 'assets'
        assets_dir.mkdir(exist_ok=True)
        example_asset = assets_dir / 'example_asset.txt'
        example_asset.write_text(EXAMPLE_ASSET)
        print("✅ Created assets/example_asset.txt")
    except Exception as e:
        print(f"❌ Error creating resource directories: {e}")
        return None

    # Print next steps
    print(f"\n✅ Skill '{skill_name}' initialized successfully at {skill_dir}")
    print("\nNext steps:")
    print("1. Edit SKILL.md to complete the TODO items and update the description")
    print("2. Customize or delete the example files in scripts/, references/, and assets/")
    print("3. Run the validator when ready to check the skill structure")

    return skill_dir


def main():
    if len(sys.argv) < 4 or sys.argv[2] != '--path':
        print("Usage: init_skill.py <skill-name> --path <path>")
        print("\nSkill name requirements:")
        print("  - Hyphen-case identifier (e.g., 'data-analyzer')")
        print("  - Lowercase letters, digits, and hyphens only")
        print("  - Max 40 characters")
        print("  - Must match directory name exactly")
        print("\nExamples:")
        print("  init_skill.py my-new-skill --path skills/public")
        print("  init_skill.py my-api-helper --path skills/private")
        print("  init_skill.py custom-skill --path /custom/location")
        sys.exit(1)

    skill_name = sys.argv[1]
    path = sys.argv[3]

    print(f"🚀 Initializing skill: {skill_name}")
    print(f"   Location: {path}")
    print()

    result = init_skill(skill_name, path)

    if result:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
